[common] add ipFamilyPolicy and ipFamilies
k8s-at-home/library-charts pull request #109
Opened 2021-11-21 22:16 UTC by AlexanderBabel

**Description of the change**
This PR adds support for new configurations options for the service resource. Since 1.22 Kubernetes (more specifically the k3s version) has support for dual stack IPv4/IPv6. But if you want to use that feature, you need to specify `ipFamilyPolicy` and `ipFamilies` on services that are directly exposed (`type: LoadBalancer`). This PR enables these options.

**Benefits**
See above.

**Possible drawbacks**
None.

**Applicable issues**
None yet.

**Additional information**

**Checklist**
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).

2021-11-21 22:24 UTC, onedr0p commented on charts/stable/common/values.yaml
> +      # Specify the ip policy. Options: SingleStack, PreferDualStack, RequireDualStack
```suggestion
      # -- Specify the ip policy. Options: SingleStack, PreferDualStack, RequireDualStack
```

2021-11-21 22:24 UTC, onedr0p commented on charts/stable/common/values.yaml
> +      # The ip families that should be used. Options: IPv4, IPv6
```suggestion
      # -- The ip families that should be used. Options: IPv4, IPv6
```

2021-11-21 22:25 UTC, onedr0p requested changes
Please update this and also re-run helm docs. Thanks!

2021-11-21 22:30 UTC, onedr0p submitted a review, later dismissed

2021-11-21 22:31 UTC, onedr0p commented
Looks good to me, I'll let @bjw-s give a glance over too.

2021-11-21 22:32 UTC, onedr0p commented
Actually, one more thing. Please update the `README_CHANGELOG.md.gotmpl` and add some release notes and re0run the helm docs. Sorry I missed that before. Thanks again.

2021-11-22 09:49 UTC, bjw-s approved these changes
LGTM 🥳

2021-11-22 09:49 UTC, merged

2021-12-02 20:34 UTC, LarsAC commented
Is it possible that this change is not backwards compatible on older cluster versions ?

2021-12-02 20:39 UTC, onedr0p commented
@LarsAC maybe, what k8s version are you using?

2021-12-02 20:47 UTC, LarsAC commented
I am / was on 1.19.13, but am now upgrading to 1.21.6. Will report whether the issue persists.

2021-12-02 22:42 UTC, LarsAC commented
Cluster upgrade to 1.21.6 resolved the issue.