[common] add global labels, with merge support
k8s-at-home/library-charts pull request #155
Opened 2022-04-20 20:29 UTC by cornfeedhobo

**Description of the change**

This PR adds support for adding labels to all created resources, as well as updates all references to use merged objects.

**Benefits**

Makes it easier than drilling down to each resource

**Possible drawbacks**

Large blast radius

**Applicable issues**

- closes #154
- fixes #153

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).

2022-04-20 20:45 UTC, onedr0p commented
I changed the branch to merge into development, you have 1 conflict that needs to be resolved.

2022-04-21 04:22 UTC, cornfeedhobo commented
I've gone ahead and rebased :crossed_fingers:

2022-04-24 14:30 UTC, cornfeedhobo commented
I was finally able to make sense of the error. I had a small typo. Considering the blast radius, it'd be great to get more than a single reviewer, and I'm in no rush to see this land.

2022-04-25 18:22 UTC, bjw-s requested changes
I went over the changes, and they look good 👍 Great job on the consistency.
There _is_ a tiny change requested, but other than that I think it should be good to merge.

2022-04-25 18:22 UTC, bjw-s commented on charts/stable/common/values.yaml
> +  # -- Set additional global label. Helm templates can be used.
```suggestion
  # -- Set additional global labels. Helm templates can be used.
```

2022-04-27 07:57 UTC, cornfeedhobo commented on charts/stable/common/values.yaml
> +  # -- Set additional global label. Helm templates can be used.
Fixed. I also caught a double space. Thanks!

2022-04-28 15:53 UTC, merged