Add support checksum/config annotation to automate roll deployments.
k8s-at-home/library-charts pull request #163
Opened 2022-05-12 18:24 UTC by Amos-85

**Description of the change**
Add support checksum/config annotation to automate roll deployments.

**Benefits**
As long as we change configuration, we want it will take effect right after running helm upgrade and redeploy the pods.

**Possible drawbacks**
N/A

**Applicable issues**

N/A

**Additional information**
[automatically-roll-deployments](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments)

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).

2022-05-13 07:09 UTC, bjw-s requested changes
Hi @Amos-85, thanks for submitting this PR! I've requested a few small changes.

Could you also maybe add unit tests for these changes (they are under `./helper-charts/common-test/tests/controller`)? Feel free to reach out if you need any help.

2022-05-13 07:09 UTC, bjw-s commented on charts/stable/common/README_CHANGELOG.md.gotmpl
> +- Changes in daemonset / deployment & statefulls templates.
```suggestion
```

I don't think there are any other changes to the templates?

2022-05-13 07:09 UTC, bjw-s commented on charts/stable/common/README_CHANGELOG.md.gotmpl
> +- Support checksum/config annotations for configMaps to automate roll deployments after config changes.
```suggestion
- Support checksum/config annotations for configMaps to automate roll deployments/daemonsets/statefulsets after config changes.
```

2022-05-13 11:01 UTC, Amos-85 commented
> Hi @Amos-85, thanks for submitting this PR! I've requested a few small changes.
> 
> Could you also maybe add unit tests for these changes (they are under `./helper-charts/common-test/tests/controller`)? Feel free to reach out if you need any help.

@bjw-s , I've add unit tests for the 3 controllers.
It's the first time I used this helm unittest plugin.
Let me know if need to fix something.

2022-05-22 21:42 UTC, closed without merging

2022-05-22 22:13 UTC, onedr0p commented
Any reason why you closed this @Amos-85 ?

2022-05-22 22:22 UTC, Amos-85 commented
@onedr0p,
Sorry, I've committed by mistake wrong changes that I'm taking forward on my fork and I struggle to revert them.
Anyway, I'll create a new PR with a link to the closed one.

2022-05-22 22:22 UTC, onedr0p commented
Gotcha, Thanks!