TrueNAS SCALE Compatibility Patches Part-2
k8s-at-home/library-charts pull request #26
Opened 2021-04-25 11:47 UTC by Ornias1993

**Description of the change**

Still WIP

This PR adds "HTTP" and "HTTPS" port protocols.
These protocol settings then get used for:
- A more-precise default port-name
- A more precise connection url in the post-install notes

To be done:
- Consume the settings to create a config map with connection settings for the SCALE portal button
- Use the HTTPS setting to set more precise ingress backend annotations.

**Benefits**

- Notes now contain the right connection protocol, which helps for non-http charts like Unifi-Controller
- SCALE also requires an accurate url to bind to it's "Portal" button
- It prevents confusion when https is served over a port named "http"

**Possible drawbacks**

- It does change the port names, even for existing users.
_But all cases of portnames should now contain the new defaults too_

- If users change an app from HTTP to HTTPS internally, it wouldn't get automatically detected.
_But that's also currently the case_

**Applicable issues**

None

**Additional information**

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).

2021-04-25 11:48 UTC, Ornias1993 commented
(whoops, this should've been a draft)

2021-04-25 16:38 UTC, Ornias1993 commented
Ready for review :-D

2021-04-26 05:37 UTC, bjw-s requested changes
Changes are mostly whitespace between test cases.

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/configmap.rb
> +# frozen_string_literal: true
This test won't run with the current file name. Test file names need to end with `_spec.rb` for them to be detected.

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/service_spec.rb
> +      it 'protocol is TCP be default' do
```suggestion
      it 'protocol defaults to TCP' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/service_spec.rb
> +      it 'protocol is TCP when set to TCP explicitly' do
```suggestion
      end

      it 'protocol is TCP when set to TCP explicitly' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/service_spec.rb
> +      it 'protocol is TCP when set to HTTP explicitly' do
```suggestion
      end

      it 'protocol is TCP when set to HTTP explicitly' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/service_spec.rb
> +      it 'protocol is TCP when set to HTTPS explicitly' do
```suggestion
      end

      it 'protocol is TCP when set to HTTPS explicitly' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/service_spec.rb
> +      it 'protocol is UDP when set to UDP explicitly' do
```suggestion
      end

      it 'protocol is UDP when set to UDP explicitly' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/configmap.rb
> +      it 'uses ingress path' do
```suggestion
      end

      it 'uses ingress path' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/configmap.rb
> +    describe 'configmap::portal-Ingress' do
```suggestion
    end

    describe 'configmap::portal-Ingress' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/configmap.rb
> +      it 'uses nodeport port protocol as protocol (HTTP)' do
```suggestion
      end

      it 'uses nodeport port protocol as protocol (HTTP)' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/configmap.rb
> +      it 'uses nodeport port protocol as protocol (HTTPS)' do
```suggestion
      end

      it 'uses nodeport port protocol as protocol (HTTPS)' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/configmap.rb
> +      it 'nodePort port defaults to the nodePort' do
```suggestion
      end

      it 'nodePort port defaults to the nodePort' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/configmap.rb
> +    describe 'configmap::portal-nodePort' do
```suggestion
    end

    describe 'configmap::portal-nodePort' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/configmap.rb
> +      it 'path  can be overridden' do
```suggestion
      end

      it 'path  can be overridden' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/configmap.rb
> +      it 'nodePort Host can be overridden' do
```suggestion
      end

      it 'nodePort Host can be overridden' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/configmap.rb
> +    describe 'configmap::portal-overrides' do
```suggestion
    end

    describe 'configmap::portal-overrides' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/configmap.rb
> +      it 'uses path "/" by default' do
```suggestion
      end

      it 'uses path "/" by default' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/configmap.rb
> +      it 'uses protocol "https" by default' do
```suggestion
      end

      it 'uses protocol "https" by default' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/configmap.rb
> +      it 'uses port "443" by default' do
```suggestion
      end

      it 'uses port "443" by default' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/configmap.rb
> +      it 'is named "portal"' do
```suggestion
      end

      it 'is named "portal"' do
```

2021-04-26 05:37 UTC, bjw-s commented on test/stable/common/configmap.rb
> +      it 'uses "$node_ip" by default' do
```suggestion
      end

      it 'uses "$node_ip" by default' do
```

2021-04-26 05:37 UTC, bjw-s commented on charts/stable/common/templates/classes/_portal.tpl
> +
```suggestion
```

2021-04-26 05:37 UTC, bjw-s commented on charts/stable/common/templates/classes/_portal.tpl
> +  url: {{ ( printf "%v%v%v%v%v%v" $protocol "://" $host ":" $port $path ) | quote }}
```suggestion
  url: {{ ( printf "%v://%v:%v%v" $protocol $host $port $path ) | quote }}
```

2021-04-26 08:49 UTC, Ornias1993 commented
Rebased and conflicts fixed

2021-04-26 09:07 UTC, Ornias1993 commented
I rebased this, fixed conflicts and added SCALE PVC storage to this PR (as it's a one-line change + unittest)

2021-04-27 09:31 UTC, bjw-s approved these changes

2021-04-27 09:32 UTC, merged